[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && bun run node_modules/prisma/build/index.js migrate deploy && bun src/index.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
